### ISSUE TITLE
simulatePressure:false with pressure given in the Point is not working

### ISSUE THREAD

**Issue by AmitKoMail** [steveruizok/perfect-freehand-dart#5]
Hello Steve,

Congratulations on the great library you have provided for drawing. We were completely taken up by the demo which is in Javascript. 
However, our application is in Flutter/Dart. We found that the example code and the code does not use pressure in generating the outline. If we pass the pressure from the pointer events to the third parameter in the Point and set the simulatePressure to false in the options, there is no effect of the pressure.

We are using XP_Pen Deco 3 for drawing. The same XP-PEN works great on the web demo hosted on https://perfect-freehand-example.vercel.app/

Best regards,

Amit

**Comment by adil192** [comment]
Hi @steveruizok, when can we expect a new release to pub.dev with these new changes?
